<?php

/**
 * Kinde Management API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Provides endpoints to manage your Kinde Businesses
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Users;

/**
 * UsersTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Users
 */
class UsersTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Users"
     */
    public function testUsers()
    {
        $testUsers = new Users();
        $namespacedClassname = Users::getModelsNamespace() . '\\Users';
        $this->assertSame('\\' . Users::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Users" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
        $this->markTestIncomplete(
            'Test of "users" property in "Users" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "nextToken"
     */
    public function testPropertyNextToken()
    {
        $this->markTestIncomplete(
            'Test of "nextToken" property in "Users" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Users::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
